# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      displayName: Build an image
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Free Trial(56257611-1494-4790-a465-f4ced4782366)'
        azureContainerRegistry: '{"loginServer":"techdemoacr.azurecr.io", "id" : "/subscriptions/56257611-1494-4790-a465-f4ced4782366/resourceGroups/techdemo/providers/Microsoft.ContainerRegistry/registries/techdemoacr"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        includeLatestTag: true
    - task: DotNetCoreCLI@2
      displayName: Testing
      inputs:
        command: test
        projects: '**/*Test/*.csproj'
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        action: Push services
        azureSubscription: 'Free Trial(56257611-1494-4790-a465-f4ced4782366)'
        azureContainerRegistry: '{"loginServer":"techdemoacr.azurecr.io", "id" : "/subscriptions/56257611-1494-4790-a465-f4ced4782366/resourceGroups/techdemo/providers/Microsoft.ContainerRegistry/registries/techdemoacr"}'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
        includeLatestTag: true